# Generated by Django 5.0 on 2024-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf_search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
