# Generated by Django 5.0.1 on 2025-07-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf_search", "0004_chatsession_user_pdfdocument_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
